name: Cleanup

on:
  workflow_dispatch: {}

jobs:
  purge-workflows:
    runs-on: ubuntu-latest
    environment: runner
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.3
        with:
          token: ${{ secrets.GH_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 0
