name: Main

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch: {}

jobs:
  groups:
    uses: bcmendoza/pco-gh-actions/.github/workflows/app.yaml@main
    secrets: inherit
    with:
      app: groups
      gcloud: true
  events:
    uses: bcmendoza/pco-gh-actions/.github/workflows/app.yaml@main
    secrets: inherit
    with:
      app: events
      gcloud: true
  connections:
    uses: bcmendoza/pco-gh-actions/.github/workflows/app.yaml@main
    secrets: inherit
    with:
      app: connections
